"""
Configuration file for the Regulatory Analysis Agent
"""
import os
from dotenv import load_dotenv

load_dotenv()

# API Keys
NEWSAPI_KEY = os.getenv("NEWSAPI_KEY", "")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
LANGSMITH_API_KEY = os.getenv("LANGSMITH_API_KEY", "")

# LangSmith Tracing (optional but recommended)
if LANGSMITH_API_KEY:
    os.environ["LANGSMITH_TRACING"] = "true"
    os.environ["LANGSMITH_API_KEY"] = LANGSMITH_API_KEY

# LLM Configuration
LLM_MODEL = os.getenv("LLM_MODEL", "deepseek-chat")
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0.3"))

# Research Configuration
MAX_NEWS_ARTICLES = int(os.getenv("MAX_NEWS_ARTICLES", "20"))

# Regulatory Focus Areas
REGULATORY_AREAS = [
    "cryptocurrency",
    "blockchain",
    "stablecoin",
    "digital assets",
    "DeFi",
    "NFT",
    "CBDC",
    "crypto exchange",
    "crypto custody",
    "AML/KYC",
    "taxation",
    "securities regulation"
]

# Supported Jurisdictions - All Countries and Territories
JURISDICTIONS = [
    # Major Jurisdictions and Organizations
    "European Union",
    "United States",
    "United Kingdom",
    
    # All UN Member States (alphabetical)
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    
    # Special Administrative Regions and Territories
    "Hong Kong",
    "Macau",
    "Puerto Rico",
    "Guam",
    "American Samoa",
    "Northern Mariana Islands",
    "US Virgin Islands",
    "British Virgin Islands",
    "Cayman Islands",
    "Bermuda",
    "Gibraltar",
    "Falkland Islands",
    "Greenland",
    "Faroe Islands",
    "Isle of Man",
    "Jersey",
    "Guernsey",
    "Aruba",
    "Curacao",
    "Sint Maarten",
    "French Polynesia",
    "New Caledonia",
    "Cook Islands",
    "Niue",
    "Tokelau",
    "Anguilla",
    "Montserrat",
    "Turks and Caicos Islands",
    "Saint Helena",
    "Ascension Island",
    "Tristan da Cunha",
    "Pitcairn Islands",
    "South Georgia and the South Sandwich Islands",
    "British Indian Ocean Territory",
    "Saint Pierre and Miquelon",
    "Wallis and Futuna",
    "French Guiana",
    "Guadeloupe",
    "Martinique",
    "Mayotte",
    "Reunion",
    "Saint Barthelemy",
    "Saint Martin",
    "Svalbard and Jan Mayen",
    "Aland Islands",
    "Madeira",
    "Azores",
    "Canary Islands",
    "Ceuta",
    "Melilla",
    "Northern Cyprus",
    "Abkhazia",
    "South Ossetia",
    "Transnistria",
    "Artsakh",
    "Somaliland",
    "Western Sahara",
    "Kosovo",
    "Palestinian Territories",
    "Gaza Strip",
    "West Bank"
]

# Policy Update Categories
POLICY_CATEGORIES = [
    "Compliance",
    "Risk Management",
    "AML/KYC",
    "Data Protection",
    "Operational",
    "Technology",
    "Legal"
]

